AZURE_FOUNDY_API_KEY = "4QuVbQNjYtNCct7BVFqhtimtP0MZfARoypQogRdnhCMkfX653YrWJQQJ99BGACHYHv6XJ3w3AAAAACOGBflp"
AZURE_FOUNDY_ENDPOINT = "https://abrahimi9395-5819-resource.services.ai.azure.com/api/projects/abrahimi9395-5819"
